name: Tag to release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: caijinglong/action-version-merge@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      deployments: write
      contents: write
      packages: read
